version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgis/postgis:15-3.3
    container_name: meetmates-postgres
    environment:
      POSTGRES_DB: meetmates
      POSTGRES_USER: meetmates
      POSTGRES_PASSWORD: meetmates123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meetmates-network

  # API Service (NestJS)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: meetmates-api
    environment:
      DATABASE_URL: postgresql://meetmates:meetmates123@postgres:5432/meetmates?schema=public
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - meetmates-network
    restart: unless-stopped

  # Web Service (React + Nginx)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: meetmates-web
    ports:
      - "3002:80"
    depends_on:
      - api
    networks:
      - meetmates-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  meetmates-network:
    driver: bridge

