version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: meetmates-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: meetmates
      POSTGRES_USER: meetmates
      POSTGRES_PASSWORD: meetmates123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U meetmates -d meetmates']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: meetmates-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: meetmates-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'php', '-r', 'file_get_contents("http://localhost:8080");']
      interval: 30s
      timeout: 10s
      retries: 3

  # Remove the API service for now - we'll run it locally
  # This avoids the build issues

volumes:
  postgres_data:
  redis_data: